### ISSUE TITLE
Attach file to email without having a file on disk

### ISSUE THREAD

**Issue by flipmokid** [toyokumo/tarayo#5]
Hi,

I would like to be able to add an attachment of a string/byte array/stream without having to write it to disc first. Possibly adding a key of `:filename` to the part which is used in place of the filename lookup?

**Comment by liquidz** [comment]
@flipmokid Thank you for opening this issue!

Yes, it is possible to modify to use `:filename` key instead :)
https://github.com/toyokumo/tarayo/blob/master/src/tarayo/mail/mime/multipart/body.clj#L61

I can't get started right away, but I'll try.

**Comment by liquidz** [comment]
@flipmokid Sorry for late reply.
I just released ver 0.2.0 which supports byte-array as an attachment file.

See the following example for concrete usage.
https://github.com/toyokumo/tarayo#attachment-file

I have no plan to support `InputStream` for now, because `javax.activation.DataSource` requires a **fresh** `InputStream` several times.
To support this behavior, we need to clone original `InputStream`, and I'm sure that it is easier to convert `InputStream` to byte-array than that.
